export const stages = [
    {
        vertices: [
            { id: 1, x: 100, y: 100, type: 'node', active: false },
            { id: 2, x: 200, y: 200, type: 'node', active: false },
            { id: 3, x: 300, y: 100, type: 'terminal', active: false },
            { id: 4, x: 200, y: 300, type: 'node', active: false },

        ],
        edges: [
            { id: 1, from: 1, to: 2, active: false, cost: 1 },
            { id: 2, from: 2, to: 3, active: false, cost: 3 },
            { id: 3, from: 1, to: 3, active: false, cost: 2 },
            { id: 4, from: 2, to: 4, active: false, cost: 2 },
        ],
        limitcost: 5,
        requiredpoints: 3,
        view: '0 0 400 400',
    },
    {
        vertices: [
            { id: 1, x: 300, y: 100, type: 'terminal', active: false },
            { id: 2, x: 300, y: 200, type: 'node', active: false },
            { id: 3, x: 150, y: 300, type: 'node', active: false },
            { id: 4, x: 450, y: 300, type: 'node', active: false },
            { id: 5, x: 220, y: 450, type: 'node', active: false },
            { id: 6, x: 380, y: 450, type: 'node', active: false },
        ],
        edges: [
            { id: 1, from: 2, to: 1, active: false, cost: 1 },
            { id: 2, from: 2, to: 3, active: false, cost: 2 },
            { id: 3, from: 2, to: 4, active: false, cost: 3 },
            { id: 4, from: 2, to: 5, active: false, cost: 4 },
            { id: 5, from: 4, to: 5, active: false, cost: 3 },
            { id: 6, from: 2, to: 5, active: false, cost: 2 },
            { id: 8, from: 4, to: 6, active: false, cost: 1 },
            { id: 9, from: 5, to: 6, active: false, cost: 2 },
            { id: 10, from: 3, to: 5, active: false, cost: 3 },
            { id: 11, from: 3, to: 6, active: false, cost: 3 },
            { id: 12, from: 2, to: 6, active: false, cost: 4 },
        ],
        limitcost: 8,
        requiredpoints: 5,
        view: '0 0 600 600',
    },
    {
        vertices: [
            { id: 1, x: 100, y: 100, type: 'node', active: false },
            { id: 2, x: 200, y: 150, type: 'node', active: false },
            { id: 3, x: 300, y: 150, type: 'hub', active: false },
            { id: 4, x: 100, y: 250, type: 'node', active: false },
            { id: 5, x: 200, y: 250, type: 'terminal', active: false },
            { id: 6, x: 400, y: 300, type: 'node', active: false },
            { id: 7, x: 300, y: 300, type: 'hub', active: false },
            { id: 8, x: 400, y: 150, type: 'terminal', active: false },
            { id: 9, x: 500, y: 200, type: 'node', active: false },

        ],
        edges: [
            { id: 1, from: 1, to: 2, active: false, cost: 2 },
            { id: 2, from: 2, to: 3, active: false, cost: 1 },
            { id: 3, from: 3, to: 4, active: false, cost: 3 },
            { id: 4, from: 4, to: 5, active: false, cost: 2 },
            { id: 5, from: 3, to: 6, active: false, cost: 2 },
            { id: 6, from: 6, to: 7, active: false, cost: 1 },
            { id: 7, from: 7, to: 3, active: false, cost: 2 },
            { id: 8, from: 5, to: 7, active: false, cost: 1 },
            { id: 9, from: 8, to: 6, active: false, cost: 3 },
            { id: 10, from: 8, to: 3, active: false, cost: 2 },
            { id: 11, from: 9, to: 8, active: false, cost: 3 },
            { id: 12, from: 9, to: 6, active: false, cost: 2 },
            { id: 13, from: 1, to: 4, active: false, cost: 1 },
        ],
        limitcost: 9,
        requiredpoints: 5,
        view: '0 0 600 400',
    },
    {
        vertices: [
            { id: 1, x: 100, y: 100, type: 'node', active: false },
            { id: 2, x: 200, y: 100, type: 'hub', active: false },
            { id: 3, x: 300, y: 100, type: 'node', active: false },
            { id: 4, x: 100, y: 200, type: 'terminal', active: false },
            { id: 5, x: 200, y: 200, type: 'node', active: false },
            { id: 6, x: 300, y: 200, type: 'node', active: false },
            { id: 7, x: 100, y: 300, type: 'node', active: false },
            { id: 8, x: 200, y: 300, type: 'node', active: false },
            { id: 9, x: 300, y: 300, type: 'terminal', active: false },
            { id: 10, x: 400, y: 100, type: 'node', active: false },
            { id: 11, x: 400, y: 200, type: 'hub', active: false },
            { id: 12, x: 400, y: 300, type: 'node', active: false },
        ],
        edges: [
            { id: 1, from: 1, to: 2, active: false, cost: 1 },
            { id: 2, from: 2, to: 3, active: false, cost: 2 },
            { id: 3, from: 1, to: 4, active: false, cost: 3 },
            { id: 4, from: 2, to: 5, active: false, cost: 1 },
            { id: 5, from: 3, to: 6, active: false, cost: 3 },
            { id: 6, from: 4, to: 7, active: false, cost: 2 },
            { id: 7, from: 5, to: 8, active: false, cost: 2 },
            { id: 8, from: 6, to: 9, active: false, cost: 2 },
            { id: 9, from: 7, to: 8, active: false, cost: 1 },
            { id: 10, from: 8, to: 9, active: false, cost: 1 },
            { id: 11, from: 3, to: 10, active: false, cost: 1 },
            { id: 12, from: 6, to: 11, active: false, cost: 2 },
            { id: 13, from: 9, to: 12, active: false, cost: 2 },
            { id: 14, from: 10, to: 11, active: false, cost: 1 },
            { id: 15, from: 11, to: 12, active: false, cost: 2 },
        ],
        limitcost: 14,
        requiredpoints: 8,
        view: '0 0 500 400',
    },
    {
        vertices: [
            { id: 1, x: 100, y: 100, type: 'node', active: false },
            { id: 2, x: 200, y: 100, type: 'hub', active: false },
            { id: 3, x: 300, y: 100, type: 'node', active: false },
            { id: 4, x: 400, y: 100, type: 'terminal', active: false },
            { id: 5, x: 100, y: 200, type: 'node', active: false },
            { id: 6, x: 200, y: 200, type: 'node', active: false },
            { id: 7, x: 300, y: 200, type: 'hub', active: false },
            { id: 8, x: 400, y: 200, type: 'node', active: false },
            { id: 9, x: 100, y: 300, type: 'terminal', active: false },
            { id: 10, x: 200, y: 300, type: 'node', active: false },
            { id: 11, x: 300, y: 300, type: 'node', active: false },
            { id: 12, x: 400, y: 300, type: 'hub', active: false },
            { id: 13, x: 100, y: 400, type: 'node', active: false },
            { id: 14, x: 200, y: 400, type: 'terminal', active: false },
            { id: 15, x: 300, y: 400, type: 'node', active: false },
            { id: 16, x: 400, y: 400, type: 'node', active: false },
            { id: 17, x: 500, y: 100, type: 'hub', active: false },
            { id: 18, x: 500, y: 200, type: 'terminal', active: false },
            { id: 19, x: 500, y: 300, type: 'node', active: false },
            { id: 20, x: 500, y: 400, type: 'node', active: false },
        ],
        edges: [
            { id: 1, from: 1, to: 2, active: false, cost: 2 },
            { id: 2, from: 2, to: 3, active: false, cost: 1 },
            { id: 4, from: 1, to: 5, active: false, cost: 2 },
            { id: 5, from: 2, to: 6, active: false, cost: 2 },
            { id: 6, from: 3, to: 7, active: false, cost: 1 },
            { id: 7, from: 4, to: 8, active: false, cost: 2 },
            { id: 8, from: 5, to: 9, active: false, cost: 3 },
            { id: 9, from: 6, to: 10, active: false, cost: 1 },
            { id: 10, from: 7, to: 11, active: false, cost: 2 },
            { id: 11, from: 8, to: 12, active: false, cost: 1 },
            { id: 12, from: 9, to: 13, active: false, cost: 2 },
            { id: 13, from: 10, to: 14, active: false, cost: 3 },
            { id: 14, from: 11, to: 15, active: false, cost: 2 },
            { id: 15, from: 12, to: 16, active: false, cost: 1 },
            { id: 17, from: 7, to: 4, active: false, cost: 3 },
            { id: 18, from: 12, to: 18, active: false, cost: 3 },
            { id: 19, from: 15, to: 12, active: false, cost: 1 },
            { id: 20, from: 16, to: 20, active: false, cost: 3 },
            { id: 21, from: 17, to: 18, active: false, cost: 1 },
            { id: 22, from: 18, to: 19, active: false, cost: 2 },
            { id: 23, from: 19, to: 20, active: false, cost: 1 },
            { id: 24, from: 13, to: 14, active: false, cost: 3 },
            { id: 25, from: 14, to: 11, active: false, cost: 2 },
            { id: 26, from: 17, to: 8, active: false, cost: 4 },
            { id: 27, from: 12, to: 19, active: false, cost: 1 },
        ],
        limitcost: 22,
        requiredpoints: 12,
        view: '0 0 600 600',
    },
    {
        vertices: [
            { id: 1, x: 100, y: 100, type: 'node', active: false },
            { id: 2, x: 200, y: 200, type: 'node', active: false },
            { id: 3, x: 200, y: 400, type: 'terminal', active: false },
            { id: 4, x: 300, y: 100, type: 'node', active: false },
            { id: 5, x: 300, y: 300, type: 'hub', active: false },
            { id: 6, x: 400, y: 200, type: 'node', active: false },
            { id: 7, x: 400, y: 400, type: 'terminal', active: false },
            { id: 8, x: 500, y: 100, type: 'node', active: false },
            { id: 9, x: 500, y: 300, type: 'node', active: false },
            { id: 10, x: 500, y: 400, type: 'node', active: false },
            { id: 11, x: 600, y: 100, type: 'node', active: false },
            { id: 12, x: 600, y: 200, type: 'terminal', active: false },
            { id: 13, x: 600, y: 300, type: 'hub', active: false },
            { id: 14, x: 700, y: 200, type: 'node', active: false },
            { id: 15, x: 700, y: 400, type: 'node', active: false },

        ],
        edges: [
            { id: 1, from: 1, to: 2, active: false, cost: 1 },
            { id: 2, from: 2, to: 3, active: false, cost: 3 },
            { id: 3, from: 5, to: 6, active: false, cost: 3 },
            { id: 4, from: 6, to: 8, active: false, cost: 2 },
            { id: 5, from: 6, to: 4, active: false, cost: 5 },
            { id: 6, from: 4, to: 1, active: false, cost: 3 },
            { id: 7, from: 5, to: 4, active: false, cost: 2 },
            { id: 8, from: 8, to: 9, active: false, cost: 4 },
            { id: 9, from: 5, to: 7, active: false, cost: 1 },
            { id: 10, from: 2, to: 5, active: false, cost: 2 },
            { id: 11, from: 9, to: 10, active: false, cost: 1 },
            { id: 12, from: 7, to: 10, active: false, cost: 2 },
            { id: 13, from: 8, to: 11, active: false, cost: 1 },
            { id: 14, from: 10, to: 13, active: false, cost: 3 },
            { id: 15, from: 12, to: 13, active: false, cost: 4 },
            { id: 16, from: 8, to: 12, active: false, cost: 2 },
            { id: 17, from: 13, to: 15, active: false, cost: 3 },
            { id: 18, from: 13, to: 14, active: false, cost: 2 },
            { id: 19, from: 9, to: 13, active: false, cost: 2 },
            { id: 20, from: 14, to: 15, active: false, cost: 2 },
        ],
        limitcost: 20,
        requiredpoints: 10,
        view: '0 0 800 600',
    },
    {
        vertices: [
            { id: 1, x: 50, y: 100, type: 'node', active: false },
            { id: 2, x: 150, y: 200, type: 'node', active: false },
            { id: 3, x: 250, y: 350, type: 'terminal', active: false },
            { id: 4, x: 350, y: 100, type: 'node', active: false },
            { id: 5, x: 450, y: 200, type: 'hub', active: false },
            { id: 6, x: 500, y: 350, type: 'node', active: false },
            { id: 7, x: 650, y: 100, type: 'node', active: false },
            { id: 8, x: 750, y: 200, type: 'terminal', active: false },
            { id: 9, x: 150, y: 400, type: 'hub', active: false },
            { id: 10, x: 350, y: 450, type: 'node', active: false },
            { id: 11, x: 550, y: 400, type: 'hub', active: false },
            { id: 12, x: 750, y: 500, type: 'terminal', active: false },
            { id: 13, x: 450, y: 600, type: 'node', active: false },
            { id: 14, x: 250, y: 100, type: 'node', active: false },
            { id: 15, x: 650, y: 200, type: 'node', active: false },
            { id: 16, x: 850, y: 300, type: 'hub', active: false },
            { id: 17, x: 750, y: 350, type: 'node', active: false },
            { id: 18, x: 650, y: 300, type: 'terminal', active: false },
            { id: 19, x: 400, y: 400, type: 'hub', active: false },
            { id: 20, x: 500, y: 100, type: 'hub', active: false },
        ],
        edges: [
            { id: 1, from: 1, to: 2, active: false, cost: 3 },
            { id: 2, from: 2, to: 3, active: false, cost: 4 },
            { id: 3, from: 3, to: 4, active: false, cost: 5 },
            { id: 4, from: 4, to: 5, active: false, cost: 6 },
            { id: 5, from: 5, to: 6, active: false, cost: 4 },
            { id: 6, from: 6, to: 7, active: false, cost: 5 },
            { id: 7, from: 7, to: 8, active: false, cost: 3 },
            { id: 8, from: 2, to: 9, active: false, cost: 5 },
            { id: 9, from: 9, to: 10, active: false, cost: 4 },
            { id: 10, from: 10, to: 11, active: false, cost: 6 },
            { id: 11, from: 11, to: 12, active: false, cost: 5 },
            { id: 12, from: 9, to: 13, active: false, cost: 7 },
            { id: 13, from: 13, to: 11, active: false, cost: 4 },
            { id: 14, from: 5, to: 20, active: false, cost: 3 },
            { id: 15, from: 15, to: 16, active: false, cost: 4 },
            { id: 16, from: 16, to: 17, active: false, cost: 6 },
            { id: 17, from: 17, to: 18, active: false, cost: 1 },
            { id: 18, from: 4, to: 14, active: false, cost: 4 },
            { id: 19, from: 14, to: 1, active: false, cost: 2 },
            { id: 20, from: 8, to: 16, active: false, cost: 7 },
            { id: 21, from: 12, to: 16, active: false, cost: 8 },
            { id: 22, from: 19, to: 5, active: false, cost: 3 },
            { id: 23, from: 13, to: 19, active: false, cost: 6 },
            { id: 25, from: 15, to: 20, active: false, cost: 2 },
            { id: 26, from: 3, to: 6, active: false, cost: 4 },
            { id: 27, from: 3, to: 10, active: false, cost: 8 },
            { id: 28, from: 15, to: 18, active: false, cost: 5 },
            { id: 29, from: 7, to: 20, active: false, cost: 2 },
        ],
        limitcost: 40,
        requiredpoints: 10,
        view: '0 0 1100 700',
    },



    // 他のステージ...
];